EarthNear1/Pages/Admin/AdminHub.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EarthNear1.Pages.Admin
{
    public class AdminHubModel : PageModel
    {
        public IActionResult OnPostCreateUser()
        {
            return RedirectToPage("/Users/Create");
        }
        public IActionResult OnPostCreateShift()
        {
            return RedirectToPage("/Shifts/CreateShift");
        }
        public IActionResult OnPostAllUsers()
        {
            return RedirectToPage("/Users/GetAllUsers");
        }
        public ActionResult OnPostAllShifts()
        {
            return RedirectToPage("/Shifts/GetAllShifts");
        }
        public ActionResult OnPostAllShiftUsers()
        {
            return RedirectToPage("/Types/ShiftUsers/GetAllShiftUsers");
        }
        public ActionResult OnPostCreateShiftUsers()
        {
            return RedirectToPage("/Types/ShiftUsers/CreateShiftUsers");
        }
        public ActionResult OnPostAssignBooking()
        {
            return RedirectToPage("/Book/AssignBooking");
        }
        public ActionResult OnPostAllShiftTypes()
        {
            return RedirectToPage("/Types/ShiftTypes/GetAllShiftTypes");
        }
        public ActionResult OnPostAllBookings()
        {
            return RedirectToPage("/Book/GetAllBookings");
        }
    }
}

EarthNear1/Pages/Admin/AdminHub.cshtml
@page
@model EarthNear1.Pages.Admin.AdminHubModel
@{
}

<h1>AdminHub</h1>
<form method="post">
    <div class="form-group">
        <button asp-page-handler="CreateUser" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Nyt medlem</button>
    </div>
    <div class="form-group">
        <button asp-page-handler="CreateShift" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Ny vagt</button>
    </div>
    <div class="form-group">
        <button asp-page-handler="AssignBooking" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Tildel vagt</button>
    </div>
    <div class="form-group">
        <button asp-page-handler="CreateShiftUsers" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Tilret jobtyper</button>
    </div>
    <div class="form-group">
        <button asp-page-handler="AllUsers" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Medlemsliste</button>
    </div>

    <div class="form-group">
        <button asp-page-handler="AllShifts" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Vagtliste</button>
    </div>
    <div class="form-group">
        <button asp-page-handler="AllBookings" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Bookingsliste</button>
    </div>
    <div class="form-group">
        <button asp-page-handler="AllShiftUsers" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Jobtyper</button>
    </div>
    <div class="form-group">
        <button asp-page-handler="AllShiftTypes" class="alert-info" style="padding: 14px 28px; width:33.3%; float: left">Vagttyper</button>
    </div>
</form>