EarthNear1/Models/User.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EarthNear1.Models
{
    public class User
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "Udfyld dit navn"), DisplayName("Navn")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Udfyld dit efternavn"), DisplayName("Efternavn")]
        public string AfterName { get; set; }
        [Required(ErrorMessage = "Angiv telefonnummer"), DisplayName("Telefonnummer")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Udfyld mailaddresse"), DisplayName("Mailaddresse"), EmailAddress]
        public string Email { get; set; }
        [DisplayName("Kodeord")]
        public string Password { get; set; }
        [BindProperty, Required(ErrorMessage = "{0} skal fyldes ud"), DataType(DataType.Password),
            Display(Name = "Gentag kodeord"), Compare(nameof(Password), ErrorMessage = "forkert kodeord")]
        public string Password2 { get; set; }
        [BindProperty, DataType(DataType.Password), Display(Name = "Password")]
        public string PasswordCheck { get; set; }
        [BindProperty, Required(ErrorMessage = "{0} skal fyldes ud")]
        public bool Admin { get; set; }
        public string UserImage { get; set; }

    }
}

EarthNear1/Pages/Book/GetAllBookings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EarthNear1.Interfaces;
using EarthNear1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EarthNear1.Pages.Book
{
    public class GetAllBookingsModel : PageModel
    {
        public IEnumerable<Booking> Bookings { get; private set; }

        private IBookingService bookingService;
        private IUserService userService;
        public GetAllBookingsModel(IBookingService bService, IUserService uService)
        {
            bookingService = bService;
            userService = uService;
        }
        public async Task OnGetAsync()
        {
            Bookings = await bookingService.GetAllBookingsAsync();
        }

        public async Task OnGetMyBookingsAsync(int sid)
        {
            Bookings = await bookingService.GetBookingByUserIdAsync(sid);
        }
    }
}

EarthNear1/Pages/Users/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EarthNear1.Exceptions;
using EarthNear1.Models;
using EarthNear1.Interfaces;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace EarthNear1.Pages.Users
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public User User { get; set; }
        public string InfoText { get; set; }
        public IEnumerable<User> Users { get; private set; }
        public IEnumerable<ShiftType> shiftTypes { get; set; }
        private readonly IUserService userService;
        private IShiftTypeService ShiftTypeService;
        private IWebHostEnvironment webHostEnvironment;
        [BindProperty]
        public IFormFile Photo { get; set; }
        public CreateModel(IUserService service, IWebHostEnvironment webHost, IShiftTypeService shiftType)
        {
            userService = service;
            webHostEnvironment = webHost;
            ShiftTypeService = shiftType;
        }
        public async Task OnGetAsync()
        {
            InfoText = "Opret profil";
            shiftTypes = await ShiftTypeService.GetAllShiftTypesAsync();
            Users = await userService.GetAllUsersAsync();
        }
        public async Task<IActionResult> OnPostAsync(User user)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (Photo == null)
            {
                user.UserImage = "noimage.jpg";
            }
            try
            {
                if (Photo != null)
                {
                    if (user.UserImage != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath, "/images/Photos",
                            user.UserImage);
                        System.IO.File.Delete(filePath);
                    }
                    user.UserImage = ProcessUploadedFile();
                }
                await userService.AddUserAsync(user);
                Users = await userService.GetAllUsersAsync();
            }
            catch (ExistsException e)
            {
                InfoText = $"Noget gik galt! {e.Message}";
                return Page();
            }
            catch (Exception ex)
            {
                InfoText = $"Noget gik galt! {ex.Message}";
                return Page();
            }
            return RedirectToPage("./Log/LogIn");
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;
            if(Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images/Photos");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

EarthNear1/Pages/Users/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EarthNear1.Models;
using EarthNear1.Interfaces;

namespace EarthNear1.Pages.Users
{
    public class DeleteModel : PageModel
    {
        [BindProperty]
        public User User { get; set; }
        private readonly IUserService userService;
        public DeleteModel(IUserService service)
        {
            userService = service;
        }
        public async Task OnGetAsync(int id)
        {
            User = await userService.GetUserFromIdAsync(id);
        }
        public async Task<IActionResult> OnPostAsync()
        {
            await userService.DeleteUserAsync(User);
            return RedirectToPage("Log/LogOut");
        }
    }
}

EarthNear1/Pages/Users/GetAllUsers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EarthNear1.Models;
using EarthNear1.Interfaces;

namespace EarthNear1.Pages.Users
{
    public class GetAllUsersModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string FilterCriteria { get; set; }
        public IEnumerable<User> Users { get; private set; }
        public List<ShiftType> shiftUsers { get; set; }
        private IUserService userService { get; set; }
        private IShiftUserService shiftUserService;
        public GetAllUsersModel(IUserService service, IShiftUserService shiftUser)
        {
            userService = service;
            shiftUserService = shiftUser;
        }
        public async Task OnGetAsync(int id)
        {
            if (!String.IsNullOrEmpty(FilterCriteria))
            {
                Users = await userService.GetUserByNameAsync(FilterCriteria);
            }
            else
                Users = await userService.GetAllUsersAsync();
        }
    }
}

EarthNear1/Pages/Users/Log/LogIn.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EarthNear1.Models;
using EarthNear1.Interfaces;
using EarthNear1.Services;
using Microsoft.Extensions.Logging;

namespace EarthNear1.Pages.Users.Log
{
    public class LogInModel : PageModel
    {
        private readonly ILogger<LogInModel> _logger;
        private IUserService userService;
        private LogInService logInService;
        public string AccessDenied = "";
        [BindProperty]
        public User User { get; set; }
        public LogInModel(IUserService service, LogInService logIn, ILogger<LogInModel>logger)
        {
            userService = service;
            logInService = logIn;
            _logger = logger;

        }
        public IActionResult OnGet()
        {
            return Page();
        }
        public IActionResult OnPost()
        {
            foreach(User user in userService.GetAllUsersAsync().Result)
            {
                if (user.Email == User.Email)
                {
                    if (user.Password == User.PasswordCheck)
                    {
                        logInService.UserLogIn(user);
                        return RedirectToPage("/Shifts/GetAllShifts");
                    }
                }
                AccessDenied = "Email/kodeord er ikke korrekt";
            }
            return Page();
        }
    }
}

EarthNear1/Pages/Users/Log/LogOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EarthNear1.Services;

namespace EarthNear1.Pages.Users.Log
{
    public class LogOutModel : PageModel
    {
        private LogInService logOutService;
        public LogOutModel(LogInService logOut)
        {
            logOutService = logOut;
        }
        public IActionResult OnGet()
        {
            logOutService.UserLogOut();
            return RedirectToPage("/Index");
        }
    }
}

EarthNear1/Pages/Users/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EarthNear1.Models;
using EarthNear1.Interfaces;

namespace EarthNear1.Pages.Users
{
    public class ProfileModel : PageModel
    {
        private IUserService userService;
        [BindProperty]
        public User User { get; set; }
        public ProfileModel(IUserService service)
        {
            userService = service;
        }
        public async Task<IActionResult> OnGetAsync (int? id)
        {
            if (id == null)
                return NotFound();

            User = await userService.GetUserFromIdAsync((int)id);

            if (User == null)
                return NotFound();

            return Page();
        }
        public IActionResult OnPostUpdateUser(int id)
        {
            return RedirectToPage("/Users/Update", new { id = id });
        }
        public IActionResult OnPostDeleteUser(int id)
        {
            return RedirectToPage("/Users/Delete", new { id = id });
        }
        public IActionResult OnPostCreateShiftUser(int id)
        {
            return RedirectToPage("/Types/ShiftUsers/CreateShiftUsers", new { id = id });
        }
    }
}

EarthNear1/Pages/Users/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EarthNear1.Exceptions;
using EarthNear1.Models;
using EarthNear1.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace EarthNear1.Pages.Users
{
    public class UpdateModel : PageModel
    {
        [BindProperty]
        public User User { get; set; }
        IUserService userService { get; set; }
        private IWebHostEnvironment webHostEnvironment;
        public IEnumerable<User> Users { get; private set; }
        public IFormFile Photo { get; set; }
        public UpdateModel(IUserService service, IWebHostEnvironment webHost)
        {
            userService = service;
            webHostEnvironment = webHost;
        }
        public async Task OnGetAsync(int id)
        {
            User = await userService.GetUserFromIdAsync(id);
            Users = await userService.GetAllUsersAsync();
        }
        public async Task <IActionResult> OnPostAsync(User user)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (Photo != null)
            {
                if (user.UserImage != null)
                {
                    string filePath = Path.Combine(webHostEnvironment.WebRootPath, "images/Photos", user.UserImage);
                    System.IO.File.Delete(filePath);
                }
                user.UserImage = ProcessUploadedFile();
            }
            await userService.UpdateUserAsync(user);
            Users = await userService.GetAllUsersAsync();
            return RedirectToPage("GetAllUsers");
        }
        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;
            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images/Photos");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

EarthNear1/Pages/Users/Create.cshtml
@page
@model EarthNear1.Pages.Users.CreateModel
@using EarthNear1.Services;
@using EarthNear1.Interfaces
@inject IUserService theUser
@inject IShiftTypeService theShiftType
@inject LogInService LogInService
@{
    ViewData["Title"] = "Create user";
    var userImage = "~/images/Photos/" +  "noimage.jpg";
}

<h1>Opret din profil</h1>
<h3>Når du har oprettet din profil, skal du logge ind med din email og password.</h3>
<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
<div class="alert alert-warning" role="alert">
    @Model.InfoText
</div>
<form method="post" enctype="multipart/form-data">
    <div class="media border p-3">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.User.UserImage" />
            <div class="form-group">
                <label asp-for="@Model.User.Name" class="control-label"></label>
                <input asp-for="@Model.User.Name" class="form-control" />
                <span asp-validation-for="@Model.User.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.AfterName" class="control-label"></label>
                <input asp-for="@Model.User.AfterName" class="form-control" />
                <span asp-validation-for="@Model.User.AfterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.PhoneNumber" class="control-label"></label>
                <input asp-for="@Model.User.PhoneNumber" class="form-control" />
                <span asp-validation-for="@Model.User.PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Email" class="control-label"></label>
                <input asp-for="@Model.User.Email" class="form-control" />
                <span asp-validation-for="@Model.User.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Password" class="control-label"></label>
                <input asp-for="@Model.User.Password" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Password2" class="control-label"></label>
                <input asp-for="@Model.User.Password2" class="form-control" />
                <span asp-validation-for="@Model.User.Password2" class="text-danger"></span>
            </div>

            @if (LogInService.GetLoggedUser() != null)
            {
                @if (LogInService.GetLoggedUser().Admin)
                {
                    <div class="form-group">
                        <label asp-for="@Model.User.Admin" class="control-label"></label>
                        <input type="radio" asp-for="@Model.User.Admin" value="true" />Ja
                        <input type="radio" asp-for="@Model.User.Admin" value="false" />Nej
                        <span asp-validation-for="@Model.User.Admin" class="text-danger"></span>
                    </div>
                }
            }
        </div>
        <div class="col-sm-4 offset-3">
            @*<div class="form-group">

            </div>*@
            <img class="rounded-circle" src="@userImage" asp-append-version="true" width="306" height="236" /><br />
            <div class="custom-file">
                <input asp-for="Photo" class="custom-file-input form-control" />
                <label class="custom-file-label">Indsæt profilbillede</label>
            </div>
        </div>
    </div>
    
    <br />
    <div class="form-group">
        <input type="submit" value="Opret" class="btn btn-dark" />&nbsp; | &nbsp;
        @if (LogInService.GetLoggedUser() != null)
        {
            <a asp-page="./GetAllUsers" class="btn btn-primary">Gå tilbage</a>
        }
        else
        {
            <a asp-page="./Log/LogIn" class="btn btn-primary">Gå tilbage</a>
        }
    </div>

    @section Scripts{
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().spilt("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
    }
</form>

EarthNear1/Pages/Users/Delete.cshtml
@page
@model EarthNear1.Pages.Users.DeleteModel
@{
    ViewData["Title"] = "Slet arbejder";
}

<h1>Slet profil</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            Navn:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Name)
        </dd>

        <dt class="col-sm-2">
            Efternavn:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.AfterName)
        </dd>

        <dt class="col-sm-2">
            tlf:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.PhoneNumber)
        </dd>
        
        <dt class="col-sm-2">
            Email:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt class="col-sm-2">
            Password:
        </dt>
        <dd class="form-group">
            @Html.DisplayFor(model=>model.User.Password)
        </dd>
    </dl>
    <form method="post">
        <input type="hidden" asp-for="User.UserId"/>
        <input type="submit" value="Slet" class="btn btn-danger" />
        <a asp-page="./GetAllUsers" class="btn btn-primary"><strong>Tilbage til medlemslisten</strong></a>
    </form>
</div>

EarthNear1/Pages/Users/GetAllUsers.cshtml
@page
@model EarthNear1.Pages.Users.GetAllUsersModel
@using EarthNear1.Services
@using EarthNear1.Interfaces
@inject LogInService logInService
@inject IShiftUserService theUserType
@inject IShiftTypeService theShiftType
@inject IUserService uService
@{
    ViewData["Title"] = "GetAllUsers";

}
<h1>Medlemmer</h1>

<p>
    @if (logInService.GetLoggedUser() != null)
    {
        @if (logInService.GetLoggedUser().Admin)
        {
            <a asp-page="Create" class="btn btn-primary"><strong>Ny medlem+</strong></a>
        }
    }


</p>
<form>
    <p>
        <input type="text" asp-for="FilterCriteria" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                Navn
            </th>
            <th>
                Jobstatus
            </th>
            <th>
                Nummer
            </th>
            <th>
                Email
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Users.Count() != 0)
        {
            @foreach (var item in Model.Users)
            {
                <tr>
                    <td>
                        <img src="~/images/Photos/@item.UserImage" class="rounded-circle" width="80" height="70" />
                    </td>
                    <td>
                        @item.Name
                        @item.AfterName
                    </td>
                    <td>
                        @foreach(var type in theUserType.GetUserTypes(item.UserId).Result)
                    {
                        @theShiftType.GetShiftTypeByIdAsync(type.ShiftTypeId).Result.ShiftName<br />

                        }    
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                    <td>
                        @item.Email
                    </td>
                    @if (logInService.GetLoggedUser() != null)
                    {
                        @if (logInService.GetLoggedUser().Admin)
                        {
                            <td>
                                <div class="btn-group-vertical">
                                    <a class="btn btn-primary" asp-page="/Book/GetAllBookings" asp-page-handler="MyBookings" asp-route-sid="@item.UserId"><strong>@item.Name</strong><strong>s vagter</strong></a>
                                    <br/>
                                    <a class="btn btn-primary" asp-page="/Users/Update" asp-route-id="@item.UserId"><strong>Updater medlem</strong></a>
                                    <br />
                                    <a class="btn btn-danger" asp-page="/Users/Delete" asp-route-id="@item.UserId"><strong>Slet medlem</strong></a>
                                </div>
                            </td>
                        }
                    }

                </tr>
            }
        }
    </tbody>
</table>

EarthNear1/Pages/Users/Profile.cshtml
@page
@using EarthNear1.Interfaces
@inject IShiftTypeService theShiftType
@inject IShiftUserService theUserType
@model EarthNear1.Pages.Users.ProfileModel
@{
    ViewData["Title"] = "Profile";
}

<div class="media border p-3">
    <img src="~/images/Photos/@Model.User.UserImage" class="rounded-circle" width="306" height="236" />
    <table class="table">
        <tr>
            <th>
                <label asp-for="User.Name" class="control-label"></label>
            </th>
            <td>
                @Model.User.Name
                @Model.User.AfterName
            </td>
        </tr>
        <tr>
            <th>
                <label asp-for="User.PhoneNumber" class="control-label"></label>
            </th>
            <td>
                @Model.User.PhoneNumber
            </td>
        </tr>
        <tr>
            <th>
                <label asp-for="User.Email" class="control-label"></label>
            </th>
            <td>
                @Model.User.Email
            </td>
        </tr>
        <tr>
            <th>
                <label asp-for="User.Password" class="control-label"></label>
            </th>
            <td>
                @Model.User.Password
            </td>
        </tr>
        <tr>
            <th>
                Jobtyper
            </th>
            <td>
                @foreach (var type in theUserType.GetUserTypes(Model.User.UserId).Result)
                {
                    <var>@theShiftType.GetShiftTypeByIdAsync(type.ShiftTypeId).Result.ShiftName,</var>

                }
            </td>
        </tr>
    </table>
</div>

<form method="post" asp-page-handler="CreateShiftUser">
    <p>
        <button class="btn btn-primary">Tilret jobtyper</button>
    </p>
    <input type="hidden" name="id" value="@Model.User.UserId" />
</form>
<form method="post" asp-page-handler="UpdateUser">
    <p>
        <button class="btn btn-primary">Rediger profil</button>
    </p>
    <input type="hidden" name="id" value="@Model.User.UserId" />
</form>
<form method="post" asp-page-handler="DeleteUser">
    <p>
        <button class="btn btn-danger">Slet din konto</button>
    </p>
    <input type="hidden" name="id" value="@Model.User.UserId" />
</form>

EarthNear1/Pages/Users/Update.cshtml
@page
@using EarthNear1.Services
@inject LogInService LogInService 
@model EarthNear1.Pages.Users.UpdateModel
@{
    ViewData["Title"] = "Update user";
    var photoPath = "~/images/Photos/" + (Model.User.UserImage ?? "noimage.jpg");
}

<h1>Rediger Profil</h1>

<form method="post" enctype="multipart/form-data">
    <div class="media border p-3">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.User.UserId" />
            <input type="hidden" asp-for="@Model.User.UserImage" />
            <div class="form-group">
                <label asp-for="@Model.User.Name" class="control-label"></label>
                <input asp-for="@Model.User.Name" class="form-control" />
                <span asp-validation-for="@Model.User.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.AfterName" class="control-label"></label>
                <input asp-for="@Model.User.AfterName" class="form-control" />
                <span asp-validation-for="@Model.User.AfterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.PhoneNumber" class="control-label"></label>
                <input asp-for="@Model.User.PhoneNumber" class="form-control" />
                <span asp-validation-for="@Model.User.PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Email" class="control-label"></label>
                <input asp-for="@Model.User.Email" class="form-control" />
                <span asp-validation-for="@Model.User.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Password" class="control-label"></label>
                <input asp-for="@Model.User.Password" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.User.Password2" class="control-label"></label>
                <input asp-for="@Model.User.Password2" class="form-control" />
                <span asp-validation-for="@Model.User.Password2" class="text-danger"></span>
            </div>

            @if (LogInService.GetLoggedUser().Admin)
            {
                <div class="form-group">
                    <label asp-for="@Model.User.Admin" class="control-label"></label>
                    <input type="radio" asp-for="@Model.User.Admin" value="true" />Ja
                    <input type="radio" asp-for="@Model.User.Admin" value="false" />Nej
                    <span asp-validation-for="@Model.User.Admin" class="text-danger"></span>
                </div>
            }
        </div>
        <div class="col-sm-4 offset-4">
            <img class="rounded-circle" src="@photoPath" asp-append-version="true" width="306" height="236" /><br />
            <div class="custom-file">
                <input asp-for="Photo" class="custom-file-input form-control" />
                <label class="custom-file-label">Skift profilbillede</label>
            </div>
        </div>
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Gem" class="btn btn-primary" />
    </div>

    @section scripts{
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
    }
</form>